# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1234, 901)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imgLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.imgLabel.setFont(font)
        self.imgLabel.setText("")
        self.imgLabel.setPixmap(QtGui.QPixmap("img/background.png"))
        self.imgLabel.setScaledContents(True)
        self.imgLabel.setObjectName("imgLabel")
        self.verticalLayout.addWidget(self.imgLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.imgSubmitButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgSubmitButton.sizePolicy().hasHeightForWidth())
        self.imgSubmitButton.setSizePolicy(sizePolicy)
        self.imgSubmitButton.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.imgSubmitButton.setFont(font)
        self.imgSubmitButton.setObjectName("imgSubmitButton")
        self.horizontalLayout.addWidget(self.imgSubmitButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 15)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupbox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupbox_2.setFont(font)
        self.groupbox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupbox_2.setObjectName("groupbox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupbox_2)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setContentsMargins(20, 20, 20, 20)
        self.formLayout.setSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupbox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.nameLineEdit = QtWidgets.QLineEdit(self.groupbox_2)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.label_3 = QtWidgets.QLabel(self.groupbox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sexLineEdit = QtWidgets.QLineEdit(self.groupbox_2)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.sexLineEdit.setFont(font)
        self.sexLineEdit.setObjectName("sexLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sexLineEdit)
        self.label_2 = QtWidgets.QLabel(self.groupbox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.ageLineEdit = QtWidgets.QLineEdit(self.groupbox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLineEdit.setFont(font)
        self.ageLineEdit.setObjectName("ageLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ageLineEdit)
        self.label_4 = QtWidgets.QLabel(self.groupbox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.departmentLineEdit = QtWidgets.QLineEdit(self.groupbox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.departmentLineEdit.setFont(font)
        self.departmentLineEdit.setObjectName("departmentLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.departmentLineEdit)
        self.label_5 = QtWidgets.QLabel(self.groupbox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.mainDemandsLineEdit = QtWidgets.QLineEdit(self.groupbox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.mainDemandsLineEdit.setFont(font)
        self.mainDemandsLineEdit.setObjectName("mainDemandsLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.mainDemandsLineEdit)
        self.label_6 = QtWidgets.QLabel(self.groupbox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.presentIllnessLineEdit = QtWidgets.QLineEdit(self.groupbox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.presentIllnessLineEdit.setFont(font)
        self.presentIllnessLineEdit.setObjectName("presentIllnessLineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.presentIllnessLineEdit)
        self.label_7 = QtWidgets.QLabel(self.groupbox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.previousIllnessLineEdit = QtWidgets.QLineEdit(self.groupbox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.previousIllnessLineEdit.setFont(font)
        self.previousIllnessLineEdit.setObjectName("previousIllnessLineEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.previousIllnessLineEdit)
        self.label_8 = QtWidgets.QLabel(self.groupbox_2)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.allergyLineEdit = QtWidgets.QLineEdit(self.groupbox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.allergyLineEdit.setFont(font)
        self.allergyLineEdit.setObjectName("allergyLineEdit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.allergyLineEdit)
        self.label_9 = QtWidgets.QLabel(self.groupbox_2)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.examinationLineEdit = QtWidgets.QLineEdit(self.groupbox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.examinationLineEdit.setFont(font)
        self.examinationLineEdit.setObjectName("examinationLineEdit")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.examinationLineEdit)
        self.label_10 = QtWidgets.QLabel(self.groupbox_2)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.diagnosisLineEdit = QtWidgets.QLineEdit(self.groupbox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.diagnosisLineEdit.setFont(font)
        self.diagnosisLineEdit.setObjectName("diagnosisLineEdit")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.diagnosisLineEdit)
        self.label_11 = QtWidgets.QLabel(self.groupbox_2)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.treatmentTextEdit = QtWidgets.QTextEdit(self.groupbox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.treatmentTextEdit.setFont(font)
        self.treatmentTextEdit.setObjectName("treatmentTextEdit")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.treatmentTextEdit)
        self.label_12 = QtWidgets.QLabel(self.groupbox_2)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.typeLineEdit = QtWidgets.QLineEdit(self.groupbox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.typeLineEdit.setFont(font)
        self.typeLineEdit.setObjectName("typeLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.typeLineEdit)
        self.label_13 = QtWidgets.QLabel(self.groupbox_2)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cardNumberLineEdit = QtWidgets.QLineEdit(self.groupbox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cardNumberLineEdit.setFont(font)
        self.cardNumberLineEdit.setObjectName("cardNumberLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cardNumberLineEdit)
        self.label_14 = QtWidgets.QLabel(self.groupbox_2)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.timeLineEdit = QtWidgets.QLineEdit(self.groupbox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.timeLineEdit.setFont(font)
        self.timeLineEdit.setObjectName("timeLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.timeLineEdit)
        self.horizontalLayout_2.addWidget(self.groupbox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1234, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "医疗文本识别系统"))
        self.groupBox.setTitle(_translate("MainWindow", "图片区域"))
        self.imgSubmitButton.setText(_translate("MainWindow", "上传图片"))
        self.groupbox_2.setTitle(_translate("MainWindow", "识别信息"))
        self.label.setText(_translate("MainWindow", "姓名"))
        self.label_3.setText(_translate("MainWindow", "性别"))
        self.label_2.setText(_translate("MainWindow", "年龄"))
        self.label_4.setText(_translate("MainWindow", "科室"))
        self.label_5.setText(_translate("MainWindow", "主诉"))
        self.label_6.setText(_translate("MainWindow", "现病史"))
        self.label_7.setText(_translate("MainWindow", "既往史"))
        self.label_8.setText(_translate("MainWindow", "过敏史"))
        self.label_9.setText(_translate("MainWindow", "体检"))
        self.label_10.setText(_translate("MainWindow", "初步诊断"))
        self.label_11.setText(_translate("MainWindow", "治疗意见"))
        self.label_12.setText(_translate("MainWindow", "类别"))
        self.label_13.setText(_translate("MainWindow", "门诊卡号"))
        self.label_14.setText(_translate("MainWindow", "就诊日期"))
